import { Email, Reminder, CalendarEvent } from '../types';
import { addDays, subDays, addHours } from 'date-fns';

const now = new Date();

export const MOCK_EMAILS: Email[] = [
  {
    id: 'e1',
    from: 'prof.johnson@university.edu',
    fromName: 'Dr. Johnson',
    subject: 'CS 301 — Midterm Study Guide',
    preview: 'I have attached the study guide for the upcoming midterm. Please review chapters 5–8...',
    body: `Hi everyone,\n\nI have attached the study guide for the upcoming midterm. Please review chapters 5–8 thoroughly, focusing on algorithm complexity and dynamic programming.\n\nOffice hours this week: Tuesday 2–4pm, Thursday 3–5pm.\n\nBest,\nDr. Johnson`,
    timestamp: subDays(now, 0.5),
    read: false,
    starred: true,
    labels: ['academic'],
  },
  {
    id: 'e2',
    from: 'registrar@university.edu',
    fromName: 'Registrar Office',
    subject: 'Fall 2026 Registration Opens April 1',
    preview: 'Course registration for Fall 2026 opens on April 1st at 8:00 AM. Your registration time is...',
    body: `Dear Student,\n\nCourse registration for Fall 2026 opens on April 1st at 8:00 AM. Your registration time slot is 9:15 AM. Please review your degree audit and meet with your advisor before registering.\n\nRegistrar Office`,
    timestamp: subDays(now, 1),
    read: true,
    starred: false,
    labels: ['registration'],
  },
  {
    id: 'e3',
    from: 'ta.smith@university.edu',
    fromName: 'TA Smith',
    subject: 'Lab 4 Graded — Feedback Inside',
    preview: 'Your Lab 4 submission has been graded. You received 87/100. See feedback below...',
    body: `Hi,\n\nYour Lab 4 submission has been graded. You received 87/100.\n\nFeedback:\n- Algorithm implementation: 42/50 — Good use of BFS but edge cases not handled.\n- Documentation: 25/25 — Excellent.\n- Testing: 20/25 — Add more edge case tests.\n\nTA Smith`,
    timestamp: subDays(now, 1.5),
    read: false,
    starred: false,
    labels: ['grade'],
  },
  {
    id: 'e4',
    from: 'studentservices@university.edu',
    fromName: 'Student Services',
    subject: 'Career Fair — March 28th',
    preview: 'The Spring Career Fair is happening March 28th in the Student Union. Over 80 companies...',
    body: `Dear Student,\n\nThe Spring Career Fair is happening March 28th in the Student Union, 10 AM – 3 PM. Over 80 companies will be in attendance, including Google, Microsoft, Amazon, and local startups.\n\nBring your resume and dress professionally!\n\nStudent Services`,
    timestamp: subDays(now, 2),
    read: true,
    starred: true,
    labels: ['career'],
  },
  {
    id: 'e5',
    from: 'noreply@github.com',
    fromName: 'GitHub',
    subject: 'Your pull request was merged',
    preview: 'Pull request #42 "Add dark mode support" was successfully merged into main...',
    body: `Your pull request #42 "Add dark mode support" was successfully merged into main by @teammate.\n\nView the merged pull request at github.com/your-org/your-repo/pull/42`,
    timestamp: subDays(now, 2.5),
    read: true,
    starred: false,
    labels: ['github'],
  },
];

export const MOCK_REMINDERS: Reminder[] = [
  {
    id: 'r1',
    title: 'Review CS 301 midterm guide',
    dueDate: addDays(now, 1),
    completed: false,
    priority: 'high',
  },
  {
    id: 'r2',
    title: 'Submit Math homework before midnight',
    dueDate: addDays(now, 0),
    completed: false,
    priority: 'high',
  },
  {
    id: 'r3',
    title: 'Schedule advisor meeting for registration',
    dueDate: addDays(now, 3),
    completed: false,
    priority: 'medium',
  },
  {
    id: 'r4',
    title: 'Prepare resume for career fair',
    dueDate: addDays(now, 7),
    completed: true,
    priority: 'medium',
  },
];

export const MOCK_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 'ce1',
    title: 'CS 301 Lecture',
    startDate: addHours(new Date(now.setHours(10, 0, 0, 0)), 0),
    endDate: addHours(new Date(now.setHours(10, 0, 0, 0)), 1.5),
    allDay: false,
    location: 'Engineering Hall 201',
    color: '#6366F1',
    source: 'personal',
  },
  {
    id: 'ce2',
    title: 'Math 201 Lecture',
    startDate: addHours(new Date(now.setHours(13, 0, 0, 0)), 0),
    endDate: addHours(new Date(now.setHours(13, 0, 0, 0)), 1),
    allDay: false,
    location: 'Science Building 105',
    color: '#8B5CF6',
    source: 'personal',
  },
  {
    id: 'ce3',
    title: 'Study Group — CS Midterm',
    startDate: addDays(addHours(new Date(now.setHours(16, 0, 0, 0)), 0), 1),
    endDate: addDays(addHours(new Date(now.setHours(16, 0, 0, 0)), 2), 1),
    allDay: false,
    location: 'Library Room 3B',
    color: '#38BDF8',
    source: 'personal',
  },
  {
    id: 'ce4',
    title: 'Spring Career Fair',
    startDate: addDays(addHours(new Date(now.setHours(10, 0, 0, 0)), 0), 7),
    endDate: addDays(addHours(new Date(now.setHours(10, 0, 0, 0)), 5), 7),
    allDay: false,
    location: 'Student Union',
    color: '#F59E0B',
    source: 'personal',
  },
  {
    id: 'ce5',
    title: "Dr. Johnson's Office Hours",
    startDate: addDays(addHours(new Date(now.setHours(14, 0, 0, 0)), 0), 1),
    endDate: addDays(addHours(new Date(now.setHours(14, 0, 0, 0)), 2), 1),
    allDay: false,
    location: 'CS Building 412',
    color: '#34D399',
    source: 'personal',
  },
];
